### ISSUE TITLE
Configure Logging 

### ISSUE THREAD

**Issue by IanFH** [AY2324S2-CS2113-T11-3/tp#53]
# Issue:
- [x] File handler is not working, only log to console is working and .xml file is not created

# TODO:
- [x] Add logging to `addFlowers`
- [x] Add logging to `removeFlowers`
- [x] Add logging to `exitCommand`
